image: vvakame/review:5.5

build-pdf:
  script: # build-in-docker.sh の終盤と同じもの
    - ./setup.sh
    - npm run pdf
  artifacts:
    paths:
      - articles/ReVIEW-Template.pdf
  tags:
    - docker

# 文法はこちらを参照してください
# https://docs.gitlab.com/ce/ci/yaml/README.html
